openapi: 3.0.0
servers:
  - description: ml-team-2-service
    url: http://ml-team-2-service/
  - description: ml-team-2-service
    url: http://localhost:8081/
  - description: ml-team-2-service
    url: http://localhost:80/
info:
  version: "0.0.1"
  title: ml-team-2-service
tags:
  - name: public
  - name: private
paths:
  /recommendations/<user_id>/:
    get:
      description: Получить рекомендации по конкретному пользователю
      tags:
        - public
      parameters:
        - in: query
          name: offset
          required: false
          description: Смещение по списку с id вин
          schema:
            type: integer
            default: 0
        - in: query
          name: amount
          required: false
          description: Количество id вин в ответе
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Список id вин
          content:
            application/json:
              schema:
                type: object
                properties:
                  wine_id:
                    type: array
                    items:
                      type: integer
                    example: [1,2,3]
        '400':
          description: bad input parameter
  /review/:
    post:
      tags:
        - private
      description: Добавить или изменить оценку вину от пользователя
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: integer
        - in: query
          name: wine_id
          required: true
          schema:
            type: integer
        - in: query
          name: rating
          required: true
          schema:
            type: integer
        - in: query
          name: variants
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Оценка добавлена
        '400':
          description: Ошибка в запросе
  /users/:
    get:
      tags:
        - private
      description: Получить список всех пользователей
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    internal_id:
                      type: integer
        '400':
          description: bad input parameter
    post:
      tags:
        - private
      description: Добавить пользователя
      parameters:
        - in: query
          name: internal_id
          required: false
          description: id пользователя в user-service
          schema:
            type: integer
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  internal_id:
                    type: integer
        '400':
          description: bad input parameter
  /wines/:
    get:
      tags:
        - private
      description: Получить список всех вин
      responses:
        '200':
          description: Список вин
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    internal_id:
                      type: integer
                    all_names:
                      type: string
        '400':
          description: bad input parameter
    post:
      tags:
        - private
      description: Добавить вино
      parameters:
        - in: query
          name: internal_id
          required: false
          description: id вина в catalog-service
          schema:
            type: integer
        - in: query
          name: all_names
          required: false
          description: все названия вин, разделенные символом |
          schema:
            type: integer
      responses:
        '200':
          description: Список пользователей
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  internal_id:
                    type: integer
                  all_names:
                    type: string
        '400':
          description: bad input parameter
  /print/:
    get:
      tags:
        - private
      description: Вывести в терминал матрицу смежности
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: object