# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segmentation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="segmentation.proto",
    package="ml2_segandrec_service",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x12segmentation.proto\x12\x15ml2_segandrec_service"@\n\x0cSegmentation\x12\x11\n\tsegm_link\x18\x01 \x01(\t\x12\x11\n\tmask_link\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x03\x62\x06proto3',
)


_SEGMENTATION = _descriptor.Descriptor(
    name="Segmentation",
    full_name="ml2_segandrec_service.Segmentation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="segm_link",
            full_name="ml2_segandrec_service.Segmentation.segm_link",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="mask_link",
            full_name="ml2_segandrec_service.Segmentation.mask_link",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="id",
            full_name="ml2_segandrec_service.Segmentation.id",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=45,
    serialized_end=109,
)

DESCRIPTOR.message_types_by_name["Segmentation"] = _SEGMENTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Segmentation = _reflection.GeneratedProtocolMessageType(
    "Segmentation",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEGMENTATION,
        "__module__": "segmentation_pb2"
        # @@protoc_insertion_point(class_scope:ml4_segandrec_service.Segmentation)
    },
)
_sym_db.RegisterMessage(Segmentation)
