# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: favorites_updated_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import entity_updated_meta_pb2 as entity__updated__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="favorites_updated_event.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\n'com.wine.to.up.user.service.api.message",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b"\n\x1d\x66\x61vorites_updated_event.proto\x1a\x19\x65ntity_updated_meta.proto\"Y\n\x15\x46\x61voritesUpdatedEvent\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x0e\n\x06wineId\x18\x02 \x01(\t\x12 \n\x04meta\x18\x03 \x01(\x0b\x32\x12.EntityUpdatedMetaB)\n'com.wine.to.up.user.service.api.messageb\x06proto3",
    dependencies=[entity__updated__meta__pb2.DESCRIPTOR,],
)


_FAVORITESUPDATEDEVENT = _descriptor.Descriptor(
    name="FavoritesUpdatedEvent",
    full_name="FavoritesUpdatedEvent",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="userId",
            full_name="FavoritesUpdatedEvent.userId",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="wineId",
            full_name="FavoritesUpdatedEvent.wineId",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="meta",
            full_name="FavoritesUpdatedEvent.meta",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=60,
    serialized_end=149,
)

_FAVORITESUPDATEDEVENT.fields_by_name[
    "meta"
].message_type = entity__updated__meta__pb2._ENTITYUPDATEDMETA
DESCRIPTOR.message_types_by_name["FavoritesUpdatedEvent"] = _FAVORITESUPDATEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FavoritesUpdatedEvent = _reflection.GeneratedProtocolMessageType(
    "FavoritesUpdatedEvent",
    (_message.Message,),
    {
        "DESCRIPTOR": _FAVORITESUPDATEDEVENT,
        "__module__": "favorites_updated_event_pb2"
        # @@protoc_insertion_point(class_scope:FavoritesUpdatedEvent)
    },
)
_sym_db.RegisterMessage(FavoritesUpdatedEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
