# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_updated_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="entity_updated_meta.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\n'com.wine.to.up.user.service.api.message",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x19\x65ntity_updated_meta.proto"\x9d\x01\n\x11\x45ntityUpdatedMeta\x12\x34\n\x0eoperation_type\x18\x01 \x01(\x0e\x32\x1c.EntityUpdatedMeta.Operation\x12\x16\n\x0eoperation_time\x18\x02 \x01(\x03":\n\tOperation\x12\n\n\x06\x43REATE\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x12\t\n\x05\x43LEAR\x10\x03\x42)\n\'com.wine.to.up.user.service.api.messageb\x06proto3',
)


_ENTITYUPDATEDMETA_OPERATION = _descriptor.EnumDescriptor(
    name="Operation",
    full_name="EntityUpdatedMeta.Operation",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="CREATE",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="DELETE",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="UPDATE",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="CLEAR",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=129,
    serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_ENTITYUPDATEDMETA_OPERATION)


_ENTITYUPDATEDMETA = _descriptor.Descriptor(
    name="EntityUpdatedMeta",
    full_name="EntityUpdatedMeta",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="operation_type",
            full_name="EntityUpdatedMeta.operation_type",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="operation_time",
            full_name="EntityUpdatedMeta.operation_time",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[_ENTITYUPDATEDMETA_OPERATION,],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=30,
    serialized_end=187,
)

_ENTITYUPDATEDMETA.fields_by_name[
    "operation_type"
].enum_type = _ENTITYUPDATEDMETA_OPERATION
_ENTITYUPDATEDMETA_OPERATION.containing_type = _ENTITYUPDATEDMETA
DESCRIPTOR.message_types_by_name["EntityUpdatedMeta"] = _ENTITYUPDATEDMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EntityUpdatedMeta = _reflection.GeneratedProtocolMessageType(
    "EntityUpdatedMeta",
    (_message.Message,),
    {
        "DESCRIPTOR": _ENTITYUPDATEDMETA,
        "__module__": "entity_updated_meta_pb2"
        # @@protoc_insertion_point(class_scope:EntityUpdatedMeta)
    },
)
_sym_db.RegisterMessage(EntityUpdatedMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
