# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_updated_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf.entity_updated_meta_pb2 as entity__updated__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="user_updated_event.proto",
    package="",
    syntax="proto3",
    serialized_options=b"\n'com.wine.to.up.user.service.api.message",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b"\n\x18user_updated_event.proto\x1a\x19\x65ntity_updated_meta.proto\"\x8a\x01\n\x10UserUpdatedEvent\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x13\n\x0bphoneNumber\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tbirthdate\x18\x04 \x01(\t\x12\x0e\n\x06\x63ityId\x18\x05 \x01(\x03\x12 \n\x04meta\x18\x06 \x01(\x0b\x32\x12.EntityUpdatedMetaB)\n'com.wine.to.up.user.service.api.messageb\x06proto3",
    dependencies=[entity__updated__meta__pb2.DESCRIPTOR,],
)


_USERUPDATEDEVENT = _descriptor.Descriptor(
    name="UserUpdatedEvent",
    full_name="UserUpdatedEvent",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="userId",
            full_name="UserUpdatedEvent.userId",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="phoneNumber",
            full_name="UserUpdatedEvent.phoneNumber",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="UserUpdatedEvent.name",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="birthdate",
            full_name="UserUpdatedEvent.birthdate",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="cityId",
            full_name="UserUpdatedEvent.cityId",
            index=4,
            number=5,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="meta",
            full_name="UserUpdatedEvent.meta",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=56,
    serialized_end=194,
)

_USERUPDATEDEVENT.fields_by_name[
    "meta"
].message_type = entity__updated__meta__pb2._ENTITYUPDATEDMETA
DESCRIPTOR.message_types_by_name["UserUpdatedEvent"] = _USERUPDATEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserUpdatedEvent = _reflection.GeneratedProtocolMessageType(
    "UserUpdatedEvent",
    (_message.Message,),
    {
        "DESCRIPTOR": _USERUPDATEDEVENT,
        "__module__": "user_updated_event_pb2"
        # @@protoc_insertion_point(class_scope:UserUpdatedEvent)
    },
)
_sym_db.RegisterMessage(UserUpdatedEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
