# Generated by Django 3.1.3 on 2020-11-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wineup", "0002_auto_20201104_0053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="internal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="internal_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
