# Generated by Django 3.1.3 on 2020-11-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wineup", "0003_auto_20201104_0258"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("wine", "user")},
        ),
    ]
